version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: "/monica by avalonia"
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
